version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_wallet
    restart: always
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet_user -d wallet_db" ]
      interval: 10s
      retries: 5
      start_period: 10s

  wallet:
    build: ./wallet  # Указываем, что код находится в папке wallet
    container_name: wallet_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: wallet_user
      SPRING_DATASOURCE_PASSWORD: wallet_password
    ports:
      - "8080:8080"

volumes:
  pg_data:
